import { Category, Product, Rubro, CustomizableProduct } from "./types";

export const categories: Category[] = [
  {
    id: "cat-cajas",
    slug: "cajas",
    name: "Cajas",
    description: "Cajas de cartón para pizza, delivery y pastelería",
    productCount: 10,
    image: "https://picsum.photos/seed/gp-cat-cajas/600/600",
    showOnHome: true,
  },
  {
    id: "cat-limpieza",
    slug: "limpieza",
    name: "Limpieza",
    description: "Químicos y soluciones de higiene profesional",
    productCount: 18,
    image: "https://picsum.photos/seed/gp-cat-limpieza/600/600",
    showOnHome: true,
  },
  {
    id: "cat-papel",
    slug: "papel-e-higiene",
    name: "Papel e Higiene",
    description: "Papel higiénico, toallas y descartables",
    productCount: 8,
    image: "https://picsum.photos/seed/gp-cat-papel/600/600",
    showOnHome: true,
  },
  {
    id: "cat-vasos",
    slug: "vasos-y-tapas",
    name: "Vasos y Tapas",
    description: "Vasos para bebidas frías y calientes con sus tapas",
    productCount: 10,
    image: "https://picsum.photos/seed/gp-cat-vasos/600/600",
    showOnHome: true,
  },
  {
    id: "cat-bolsas",
    slug: "bolsas",
    name: "Bolsas",
    description: "Camiseta, consorcio, residuos y compostables",
    productCount: 13,
    image: "https://picsum.photos/seed/gp-cat-bolsas/600/600",
    showOnHome: true,
  },
  {
    id: "cat-bandejas",
    slug: "bandejas",
    name: "Bandejas",
    description: "Aluminio, kraft, PET y sushi",
    productCount: 10,
    image: "https://picsum.photos/seed/gp-cat-bandejas/600/600",
    showOnHome: true,
  },
  {
    id: "cat-guantes",
    slug: "guantes-y-accesorios",
    name: "Guantes y Accesorios",
    description: "Nitrilo, látex, vinilo y accesorios de limpieza",
    productCount: 10,
    image: "https://picsum.photos/seed/gp-cat-guantes/600/600",
    showOnHome: true,
  },
  {
    id: "cat-personalizado",
    slug: "packaging-personalizado",
    name: "Packaging Personalizado",
    description: "Diseño e impresión a medida de tu marca",
    productCount: 0,
    image: "https://picsum.photos/seed/gp-cat-personalizado/600/600",
    showOnHome: true,
  },
  {
    id: "cat-higiene-personal",
    slug: "higiene-personal-y-lavado",
    name: "Higiene Personal y Lavado",
    description: "Jabones para manos, ropa y cuidado diario",
    productCount: 6,
    image: "https://picsum.photos/seed/gp-cat-higiene/600/600",
  },
  {
    id: "cat-baldes",
    slug: "baldes-y-residuos",
    name: "Baldes y Residuos",
    description: "Baldes, basureros y bolsas para residuos",
    productCount: 5,
    image: "https://picsum.photos/seed/gp-cat-baldes/600/600",
  },
  {
    id: "cat-elementos",
    slug: "elementos-de-limpieza",
    name: "Elementos de Limpieza",
    description: "Escobas, mopas, secadores y accesorios",
    productCount: 10,
    image: "https://picsum.photos/seed/gp-cat-elementos/600/600",
  },
  {
    id: "cat-bowls",
    slug: "bowls-y-contenedores",
    name: "Bowls y Contenedores",
    description: "Packaging moderno para alimentos y delivery",
    productCount: 10,
    image: "https://picsum.photos/seed/gp-cat-bowls/600/600",
  },
  {
    id: "cat-papeleria",
    slug: "papeleria",
    name: "Papelería",
    description: "Insumos de oficina, comercio y organización",
    productCount: 10,
    image: "https://picsum.photos/seed/gp-cat-papeleria/600/600",
  },
];

export const rubros: Rubro[] = [
  {
    id: "rubro-pizzerias",
    slug: "pizzerias",
    name: "Pizzerías",
    description: "Cajas para pizza, bolsas y papel para delivery",
    categorySlugs: ["cajas", "bolsas", "papel-e-higiene"],
    image: "https://picsum.photos/seed/gp-pizzerias/700/500",
  },
  {
    id: "rubro-cafeterias",
    slug: "cafeterias",
    name: "Cafeterías",
    description: "Vasos térmicos, tapas y bowls para servir",
    categorySlugs: ["vasos-y-tapas", "bowls-y-contenedores", "papel-e-higiene"],
    image: "https://picsum.photos/seed/gp-cafeterias/700/500",
  },
  {
    id: "rubro-hamburgueserias",
    slug: "hamburgueserias",
    name: "Hamburgueserías",
    description: "Cajas, bandejas y guantes para manipulación de alimentos",
    categorySlugs: ["cajas", "bandejas", "guantes-y-accesorios"],
    image: "https://picsum.photos/seed/gp-hamburgueserias/700/500",
  },
  {
    id: "rubro-panaderias",
    slug: "panaderias",
    name: "Panaderías",
    description: "Bolsas de papel, cajas para tortas y descartables",
    categorySlugs: ["bolsas", "cajas", "papel-e-higiene"],
    image: "https://picsum.photos/seed/gp-panaderias/700/500",
  },
  {
    id: "rubro-hoteles",
    slug: "hoteles",
    name: "Hoteles",
    description: "Limpieza, higiene y guantes en volumen",
    categorySlugs: ["limpieza", "papel-e-higiene", "guantes-y-accesorios"],
    image: "https://picsum.photos/seed/gp-hoteles/700/500",
  },
  {
    id: "rubro-empresas",
    slug: "empresas",
    name: "Empresas",
    description: "Limpieza, papelería e higiene para oficinas",
    categorySlugs: ["limpieza", "papeleria", "papel-e-higiene"],
    image: "https://picsum.photos/seed/gp-empresas/700/500",
  },
];

export const customizableProducts: CustomizableProduct[] = [
  {
    id: "cust-bolsas",
    name: "Bolsas de papel",
    description: "Bolsas kraft con manija retorcida o plana.",
    customizationType: "Impresión 1 o 2 tintas (logotipo, datos, redes sociales, etc.)",
    minQty: "500 unidades",
    printColors: "1 o 2 tintas",
    image: "https://picsum.photos/seed/gp-cust-bolsas/600/450",
  },
  {
    id: "cust-vasos",
    name: "Vasos de papel",
    description: "Vasos para bebidas frías o calientes (4oz a 16oz).",
    customizationType: "Impresión 1 a 3 tintas en el cuerpo del vaso.",
    minQty: "1.000 unidades",
    printColors: "1 a 3 tintas",
    image: "https://picsum.photos/seed/gp-cust-vasos/600/450",
  },
  {
    id: "cust-cajas",
    name: "Cajas de cartón",
    description: "Cajas para pizza, tortas, hamburguesas y delivery.",
    customizationType: "Impresión 1 a 2 tintas en tapa o laterales.",
    minQty: "300 unidades",
    printColors: "1 o 2 tintas",
    image: "https://picsum.photos/seed/gp-cust-cajas/600/450",
  },
  {
    id: "cust-papel-antigrasa",
    name: "Papel Antigrasa",
    description: "Papel antigrasa personalizado para envolver alimentos.",
    customizationType: "Impresión 1 tinta con diseño repetido o full print.",
    minQty: "1.000 hojas",
    printColors: "1 tinta",
    image: "https://picsum.photos/seed/gp-cust-papel/600/450",
  },
  {
    id: "cust-etiquetas",
    name: "Etiquetas y Stickers",
    description: "Etiquetas adhesivas personalizadas para envases y packaging.",
    customizationType: "Impresión full color en papel o vinilo.",
    minQty: "500 unidades",
    printColors: "Full color",
    image: "https://picsum.photos/seed/gp-cust-etiquetas/600/450",
  },
];

export const products: Product[] = [
  {
    id: "p-001",
    slug: "alcohol-bidon-5-lt",
    sku: "LIM-001",
    name: "Alcohol",
    categorySlug: "limpieza",
    price: 149,
    unit: "Bidón 5 lt",
    minQty: 1,
    images: ["https://picsum.photos/seed/gp-alcohol-bidon-5-lt/800/800"],
    description: "Alcohol presentación bidón 5 lt, de uso profesional para comercios, gastronomía y empresas.",
    specs: [
      { label: "Presentación", value: "Bidón 5 lt" },
      { label: "Categoría", value: "Limpieza" },
      { label: "SKU", value: "LIM-001" }
    ],
    tags: ["limpieza"],
    inStock: true,
  },
  {
    id: "p-002",
    slug: "alcohol-bidon-10-lt",
    sku: "LIM-002",
    name: "Alcohol",
    categorySlug: "limpieza",
    price: 650,
    unit: "Bidón 10 lt",
    minQty: 1,
    images: ["https://picsum.photos/seed/gp-alcohol-bidon-10-lt/800/800"],
    description: "Alcohol presentación bidón 10 lt, de uso profesional para comercios, gastronomía y empresas.",
    specs: [
      { label: "Presentación", value: "Bidón 10 lt" },
      { label: "Categoría", value: "Limpieza" },
      { label: "SKU", value: "LIM-002" }
    ],
    tags: ["limpieza"],
    inStock: true,
  },
  {
    id: "p-003",
    slug: "alcohol-en-gel-bidon-5-lt",
    sku: "LIM-003",
    name: "Alcohol en gel",
    categorySlug: "limpieza",
    price: 775,
    unit: "Bidón 5 lt",
    minQty: 1,
    images: ["https://picsum.photos/seed/gp-alcohol-en-gel-bidon-5-lt/800/800"],
    description: "Alcohol en gel presentación bidón 5 lt, de uso profesional para comercios, gastronomía y empresas.",
    specs: [
      { label: "Presentación", value: "Bidón 5 lt" },
      { label: "Categoría", value: "Limpieza" },
      { label: "SKU", value: "LIM-003" }
    ],
    tags: ["limpieza"],
    featured: true,
    inStock: true,
  },
  {
    id: "p-004",
    slug: "amonio-bidon-5-lt",
    sku: "LIM-004",
    name: "Amonio",
    categorySlug: "limpieza",
    price: 420,
    unit: "Bidón 5 lt",
    minQty: 1,
    images: ["https://picsum.photos/seed/gp-amonio-bidon-5-lt/800/800"],
    description: "Amonio presentación bidón 5 lt, de uso profesional para comercios, gastronomía y empresas.",
    specs: [
      { label: "Presentación", value: "Bidón 5 lt" },
      { label: "Categoría", value: "Limpieza" },
      { label: "SKU", value: "LIM-004" }
    ],
    tags: ["limpieza"],
    inStock: false,
  },
  {
    id: "p-005",
    slug: "cera-1-lt",
    sku: "LIM-005",
    name: "Cera",
    categorySlug: "limpieza",
    price: 315,
    unit: "1 lt",
    minQty: 1,
    images: ["https://picsum.photos/seed/gp-cera-1-lt/800/800"],
    description: "Cera presentación 1 lt, de uso profesional para comercios, gastronomía y empresas.",
    specs: [
      { label: "Presentación", value: "1 lt" },
      { label: "Categoría", value: "Limpieza" },
      { label: "SKU", value: "LIM-005" }
    ],
    tags: ["limpieza"],
    inStock: true,
  },
  {
    id: "p-006",
    slug: "cera-al-agua-bidon-5-lt",
    sku: "LIM-006",
    name: "Cera al agua",
    categorySlug: "limpieza",
    price: 510,
    unit: "Bidón 5 lt",
    minQty: 1,
    images: ["https://picsum.photos/seed/gp-cera-al-agua-bidon-5-lt/800/800"],
    description: "Cera al agua presentación bidón 5 lt, de uso profesional para comercios, gastronomía y empresas.",
    specs: [
      { label: "Presentación", value: "Bidón 5 lt" },
      { label: "Categoría", value: "Limpieza" },
      { label: "SKU", value: "LIM-006" }
    ],
    tags: ["limpieza"],
    inStock: true,
  },
  {
    id: "p-007",
    slug: "desengrasante-bidon-5-lt",
    sku: "LIM-007",
    name: "Desengrasante",
    categorySlug: "limpieza",
    price: 644,
    unit: "Bidón 5 lt",
    minQty: 1,
    images: ["https://picsum.photos/seed/gp-desengrasante-bidon-5-lt/800/800"],
    description: "Desengrasante presentación bidón 5 lt, de uso profesional para comercios, gastronomía y empresas.",
    specs: [
      { label: "Presentación", value: "Bidón 5 lt" },
      { label: "Categoría", value: "Limpieza" },
      { label: "SKU", value: "LIM-007" }
    ],
    tags: ["limpieza"],
    inStock: true,
  },
  {
    id: "p-008",
    slug: "detergente-biodegradable-bidon-5-lt",
    sku: "LIM-008",
    name: "Detergente biodegradable",
    categorySlug: "limpieza",
    price: 225,
    unit: "Bidón 5 lt",
    minQty: 1,
    images: ["https://picsum.photos/seed/gp-detergente-biodegradable-bidon-5-lt/800/800"],
    description: "Detergente biodegradable presentación bidón 5 lt, de uso profesional para comercios, gastronomía y empresas.",
    specs: [
      { label: "Presentación", value: "Bidón 5 lt" },
      { label: "Categoría", value: "Limpieza" },
      { label: "SKU", value: "LIM-008" }
    ],
    tags: ["limpieza"],
    features: ["Ecológico"],
    inStock: true,
  },
  {
    id: "p-009",
    slug: "detergente-concentrado-bidon-5-lt",
    sku: "LIM-009",
    name: "Detergente concentrado",
    categorySlug: "limpieza",
    price: 198,
    unit: "Bidón 5 lt",
    minQty: 1,
    images: ["https://picsum.photos/seed/gp-detergente-concentrado-bidon-5-lt/800/800"],
    description: "Detergente concentrado presentación bidón 5 lt, de uso profesional para comercios, gastronomía y empresas.",
    specs: [
      { label: "Presentación", value: "Bidón 5 lt" },
      { label: "Categoría", value: "Limpieza" },
      { label: "SKU", value: "LIM-009" }
    ],
    tags: ["limpieza"],
    inStock: true,
  },
  {
    id: "p-010",
    slug: "hipoclorito-bidon-5-lt",
    sku: "LIM-010",
    name: "Hipoclorito",
    categorySlug: "limpieza",
    price: 115,
    unit: "Bidón 5 lt",
    minQty: 1,
    images: ["https://picsum.photos/seed/gp-hipoclorito-bidon-5-lt/800/800"],
    description: "Hipoclorito presentación bidón 5 lt, de uso profesional para comercios, gastronomía y empresas.",
    specs: [
      { label: "Presentación", value: "Bidón 5 lt" },
      { label: "Categoría", value: "Limpieza" },
      { label: "SKU", value: "LIM-010" }
    ],
    tags: ["limpieza"],
    inStock: true,
  },
  {
    id: "p-011",
    slug: "lavandina-en-gel-700-ml",
    sku: "LIM-011",
    name: "Lavandina en gel",
    categorySlug: "limpieza",
    price: 190,
    unit: "700 ml",
    minQty: 1,
    images: ["https://picsum.photos/seed/gp-lavandina-en-gel-700-ml/800/800"],
    description: "Lavandina en gel presentación 700 ml, de uso profesional para comercios, gastronomía y empresas.",
    specs: [
      { label: "Presentación", value: "700 ml" },
      { label: "Categoría", value: "Limpieza" },
      { label: "SKU", value: "LIM-011" }
    ],
    tags: ["limpieza"],
    inStock: true,
  },
  {
    id: "p-012",
    slug: "lavavajillas-10-lt",
    sku: "LIM-012",
    name: "Lavavajillas",
    categorySlug: "limpieza",
    price: 1675,
    unit: "10 lt",
    minQty: 1,
    images: ["https://picsum.photos/seed/gp-lavavajillas-10-lt/800/800"],
    description: "Lavavajillas presentación 10 lt, de uso profesional para comercios, gastronomía y empresas.",
    specs: [
      { label: "Presentación", value: "10 lt" },
      { label: "Categoría", value: "Limpieza" },
      { label: "SKU", value: "LIM-012" }
    ],
    tags: ["limpieza"],
    inStock: true,
  },
  {
    id: "p-013",
    slug: "limpia-horno-jupiter-360-g",
    sku: "LIM-013",
    name: "Limpia horno Júpiter",
    categorySlug: "limpieza",
    price: 198,
    unit: "360 g",
    minQty: 1,
    images: ["https://picsum.photos/seed/gp-limpia-horno-jupiter-360-g/800/800"],
    description: "Limpia horno Júpiter presentación 360 g, de uso profesional para comercios, gastronomía y empresas.",
    specs: [
      { label: "Presentación", value: "360 g" },
      { label: "Categoría", value: "Limpieza" },
      { label: "SKU", value: "LIM-013" }
    ],
    tags: ["limpieza"],
    inStock: true,
  },
  {
    id: "p-014",
    slug: "limpia-vidrio-cristal-500-ml",
    sku: "LIM-014",
    name: "Limpia vidrio (cristal)",
    categorySlug: "limpieza",
    price: 175,
    unit: "500 ml",
    minQty: 1,
    images: ["https://picsum.photos/seed/gp-limpia-vidrio-cristal-500-ml/800/800"],
    description: "Limpia vidrio (cristal) presentación 500 ml, de uso profesional para comercios, gastronomía y empresas.",
    specs: [
      { label: "Presentación", value: "500 ml" },
      { label: "Categoría", value: "Limpieza" },
      { label: "SKU", value: "LIM-014" }
    ],
    tags: ["limpieza"],
    featured: true,
    inStock: true,
  },
  {
    id: "p-015",
    slug: "limpiador-multiuso-pro-bidon-5-lt",
    sku: "LIM-015",
    name: "Limpiador multiuso PRO",
    categorySlug: "limpieza",
    price: 640,
    unit: "Bidón 5 lt",
    minQty: 1,
    images: ["https://picsum.photos/seed/gp-limpiador-multiuso-pro-bidon-5-lt/800/800"],
    description: "Limpiador multiuso PRO presentación bidón 5 lt, de uso profesional para comercios, gastronomía y empresas.",
    specs: [
      { label: "Presentación", value: "Bidón 5 lt" },
      { label: "Categoría", value: "Limpieza" },
      { label: "SKU", value: "LIM-015" }
    ],
    tags: ["limpieza"],
    inStock: true,
  },
  {
    id: "p-016",
    slug: "saca-sarro-500-ml",
    sku: "LIM-016",
    name: "Saca sarro",
    categorySlug: "limpieza",
    price: 190,
    unit: "500 ml",
    minQty: 1,
    images: ["https://picsum.photos/seed/gp-saca-sarro-500-ml/800/800"],
    description: "Saca sarro presentación 500 ml, de uso profesional para comercios, gastronomía y empresas.",
    specs: [
      { label: "Presentación", value: "500 ml" },
      { label: "Categoría", value: "Limpieza" },
      { label: "SKU", value: "LIM-016" }
    ],
    tags: ["limpieza"],
    inStock: true,
  },
  {
    id: "p-017",
    slug: "aromatizante-ambiente-spray-360-ml",
    sku: "LIM-017",
    name: "Aromatizante ambiente spray",
    categorySlug: "limpieza",
    price: 145,
    unit: "360 ml",
    minQty: 1,
    images: ["https://picsum.photos/seed/gp-aromatizante-ambiente-spray-360-ml/800/800"],
    description: "Aromatizante ambiente spray presentación 360 ml, de uso profesional para comercios, gastronomía y empresas.",
    specs: [
      { label: "Presentación", value: "360 ml" },
      { label: "Categoría", value: "Limpieza" },
      { label: "SKU", value: "LIM-017" }
    ],
    tags: ["limpieza"],
    inStock: true,
  },
  {
    id: "p-018",
    slug: "desinfectante-ambiente-spray-360-ml",
    sku: "LIM-018",
    name: "Desinfectante ambiente spray",
    categorySlug: "limpieza",
    price: 145,
    unit: "360 ml",
    minQty: 1,
    images: ["https://picsum.photos/seed/gp-desinfectante-ambiente-spray-360-ml/800/800"],
    description: "Desinfectante ambiente spray presentación 360 ml, de uso profesional para comercios, gastronomía y empresas.",
    specs: [
      { label: "Presentación", value: "360 ml" },
      { label: "Categoría", value: "Limpieza" },
      { label: "SKU", value: "LIM-018" }
    ],
    tags: ["limpieza"],
    inStock: true,
  },
  {
    id: "p-019",
    slug: "jabon-para-manos-1-lt",
    sku: "HIG-001",
    name: "Jabón para manos",
    categorySlug: "higiene-personal-y-lavado",
    price: 185,
    unit: "1 lt",
    minQty: 1,
    images: ["https://picsum.photos/seed/gp-jabon-para-manos-1-lt/800/800"],
    description: "Jabón para manos presentación 1 lt, de uso profesional para comercios, gastronomía y empresas.",
    specs: [
      { label: "Presentación", value: "1 lt" },
      { label: "Categoría", value: "Higiene Personal y Lavado" },
      { label: "SKU", value: "HIG-001" }
    ],
    tags: ["higiene personal y lavado"],
    featured: true,
    inStock: false,
  },
  {
    id: "p-020",
    slug: "jabon-para-manos-bidon-5-lt",
    sku: "HIG-002",
    name: "Jabón para manos",
    categorySlug: "higiene-personal-y-lavado",
    price: 575,
    unit: "Bidón 5 lt",
    minQty: 1,
    images: ["https://picsum.photos/seed/gp-jabon-para-manos-bidon-5-lt/800/800"],
    description: "Jabón para manos presentación bidón 5 lt, de uso profesional para comercios, gastronomía y empresas.",
    specs: [
      { label: "Presentación", value: "Bidón 5 lt" },
      { label: "Categoría", value: "Higiene Personal y Lavado" },
      { label: "SKU", value: "HIG-002" }
    ],
    tags: ["higiene personal y lavado"],
    inStock: true,
  },
  {
    id: "p-021",
    slug: "jabon-para-ropa-bidon-5-lt",
    sku: "HIG-003",
    name: "Jabón para ropa",
    categorySlug: "higiene-personal-y-lavado",
    price: 485,
    unit: "Bidón 5 lt",
    minQty: 1,
    images: ["https://picsum.photos/seed/gp-jabon-para-ropa-bidon-5-lt/800/800"],
    description: "Jabón para ropa presentación bidón 5 lt, de uso profesional para comercios, gastronomía y empresas.",
    specs: [
      { label: "Presentación", value: "Bidón 5 lt" },
      { label: "Categoría", value: "Higiene Personal y Lavado" },
      { label: "SKU", value: "HIG-003" }
    ],
    tags: ["higiene personal y lavado"],
    inStock: true,
  },
  {
    id: "p-022",
    slug: "suavizante-ropa-bidon-5-lt",
    sku: "HIG-004",
    name: "Suavizante ropa",
    categorySlug: "higiene-personal-y-lavado",
    price: 485,
    unit: "Bidón 5 lt",
    minQty: 1,
    images: ["https://picsum.photos/seed/gp-suavizante-ropa-bidon-5-lt/800/800"],
    description: "Suavizante ropa presentación bidón 5 lt, de uso profesional para comercios, gastronomía y empresas.",
    specs: [
      { label: "Presentación", value: "Bidón 5 lt" },
      { label: "Categoría", value: "Higiene Personal y Lavado" },
      { label: "SKU", value: "HIG-004" }
    ],
    tags: ["higiene personal y lavado"],
    inStock: true,
  },
  {
    id: "p-023",
    slug: "jabon-en-barra-conejo-unidad",
    sku: "HIG-005",
    name: "Jabón en barra Conejo",
    categorySlug: "higiene-personal-y-lavado",
    price: 65,
    unit: "Unidad",
    minQty: 1,
    images: ["https://picsum.photos/seed/gp-jabon-en-barra-conejo-unidad/800/800"],
    description: "Jabón en barra Conejo presentación unidad, de uso profesional para comercios, gastronomía y empresas.",
    specs: [
      { label: "Presentación", value: "Unidad" },
      { label: "Categoría", value: "Higiene Personal y Lavado" },
      { label: "SKU", value: "HIG-005" }
    ],
    tags: ["higiene personal y lavado"],
    inStock: true,
  },
  {
    id: "p-024",
    slug: "jabon-en-barra-dove-unidad",
    sku: "HIG-006",
    name: "Jabón en barra Dove",
    categorySlug: "higiene-personal-y-lavado",
    price: 75,
    unit: "Unidad",
    minQty: 1,
    images: ["https://picsum.photos/seed/gp-jabon-en-barra-dove-unidad/800/800"],
    description: "Jabón en barra Dove presentación unidad, de uso profesional para comercios, gastronomía y empresas.",
    specs: [
      { label: "Presentación", value: "Unidad" },
      { label: "Categoría", value: "Higiene Personal y Lavado" },
      { label: "SKU", value: "HIG-006" }
    ],
    tags: ["higiene personal y lavado"],
    inStock: true,
  },
  {
    id: "p-025",
    slug: "balde-oval-escurridor-unidad",
    sku: "BAL-001",
    name: "Balde oval escurridor",
    categorySlug: "baldes-y-residuos",
    price: 320,
    unit: "Unidad",
    minQty: 1,
    images: ["https://picsum.photos/seed/gp-balde-oval-escurridor-unidad/800/800"],
    description: "Balde oval escurridor presentación unidad, de uso profesional para comercios, gastronomía y empresas.",
    specs: [
      { label: "Presentación", value: "Unidad" },
      { label: "Categoría", value: "Baldes y Residuos" },
      { label: "SKU", value: "BAL-001" }
    ],
    tags: ["baldes y residuos"],
    inStock: true,
  },
  {
    id: "p-026",
    slug: "basurero-slim-15-lt-unidad",
    sku: "BAL-002",
    name: "Basurero slim 15 lt",
    categorySlug: "baldes-y-residuos",
    price: 890,
    unit: "Unidad",
    minQty: 1,
    images: ["https://picsum.photos/seed/gp-basurero-slim-15-lt-unidad/800/800"],
    description: "Basurero slim 15 lt presentación unidad, de uso profesional para comercios, gastronomía y empresas.",
    specs: [
      { label: "Presentación", value: "Unidad" },
      { label: "Categoría", value: "Baldes y Residuos" },
      { label: "SKU", value: "BAL-002" }
    ],
    tags: ["baldes y residuos"],
    inStock: true,
  },
  {
    id: "p-027",
    slug: "basurero-50-lt-unidad",
    sku: "BAL-003",
    name: "Basurero 50 lt",
    categorySlug: "baldes-y-residuos",
    price: 1490,
    unit: "Unidad",
    minQty: 1,
    images: ["https://picsum.photos/seed/gp-basurero-50-lt-unidad/800/800"],
    description: "Basurero 50 lt presentación unidad, de uso profesional para comercios, gastronomía y empresas.",
    specs: [
      { label: "Presentación", value: "Unidad" },
      { label: "Categoría", value: "Baldes y Residuos" },
      { label: "SKU", value: "BAL-003" }
    ],
    tags: ["baldes y residuos"],
    featured: true,
    inStock: true,
  },
  {
    id: "p-028",
    slug: "bolsa-residuo-negra-55x70-cm-paq-x100",
    sku: "BAL-004",
    name: "Bolsa residuo negra",
    categorySlug: "baldes-y-residuos",
    price: 150,
    unit: "55x70 cm (paq. x100)",
    minQty: 1,
    images: ["https://picsum.photos/seed/gp-bolsa-residuo-negra-55x70-cm-paq-x100/800/800"],
    description: "Bolsa residuo negra presentación 55x70 cm (paq. x100), de uso profesional para comercios, gastronomía y empresas.",
    specs: [
      { label: "Presentación", value: "55x70 cm (paq. x100)" },
      { label: "Categoría", value: "Baldes y Residuos" },
      { label: "SKU", value: "BAL-004" }
    ],
    tags: ["baldes y residuos"],
    inStock: true,
  },
  {
    id: "p-029",
    slug: "rollo-bolsa-70x100-rollo-x10-unidades",
    sku: "BAL-005",
    name: "Rollo bolsa 70x100",
    categorySlug: "baldes-y-residuos",
    price: 220,
    unit: "Rollo x10 unidades",
    minQty: 1,
    images: ["https://picsum.photos/seed/gp-rollo-bolsa-70x100-rollo-x10-unidades/800/800"],
    description: "Rollo bolsa 70x100 presentación rollo x10 unidades, de uso profesional para comercios, gastronomía y empresas.",
    specs: [
      { label: "Presentación", value: "Rollo x10 unidades" },
      { label: "Categoría", value: "Baldes y Residuos" },
      { label: "SKU", value: "BAL-005" }
    ],
    tags: ["baldes y residuos"],
    inStock: true,
  },
  {
    id: "p-030",
    slug: "escoba-doble-barrido-unidad",
    sku: "ELE-001",
    name: "Escoba doble barrido",
    categorySlug: "elementos-de-limpieza",
    price: 390,
    unit: "Unidad",
    minQty: 1,
    images: ["https://picsum.photos/seed/gp-escoba-doble-barrido-unidad/800/800"],
    description: "Escoba doble barrido presentación unidad, de uso profesional para comercios, gastronomía y empresas.",
    specs: [
      { label: "Presentación", value: "Unidad" },
      { label: "Categoría", value: "Elementos de Limpieza" },
      { label: "SKU", value: "ELE-001" }
    ],
    tags: ["elementos de limpieza"],
    featured: true,
    inStock: true,
  },
  {
    id: "p-031",
    slug: "escoba-exterior-unidad",
    sku: "ELE-002",
    name: "Escoba exterior",
    categorySlug: "elementos-de-limpieza",
    price: 280,
    unit: "Unidad",
    minQty: 1,
    images: ["https://picsum.photos/seed/gp-escoba-exterior-unidad/800/800"],
    description: "Escoba exterior presentación unidad, de uso profesional para comercios, gastronomía y empresas.",
    specs: [
      { label: "Presentación", value: "Unidad" },
      { label: "Categoría", value: "Elementos de Limpieza" },
      { label: "SKU", value: "ELE-002" }
    ],
    tags: ["elementos de limpieza"],
    inStock: true,
  },
  {
    id: "p-032",
    slug: "pala-de-mano-unidad",
    sku: "ELE-003",
    name: "Pala de mano",
    categorySlug: "elementos-de-limpieza",
    price: 170,
    unit: "Unidad",
    minQty: 1,
    images: ["https://picsum.photos/seed/gp-pala-de-mano-unidad/800/800"],
    description: "Pala de mano presentación unidad, de uso profesional para comercios, gastronomía y empresas.",
    specs: [
      { label: "Presentación", value: "Unidad" },
      { label: "Categoría", value: "Elementos de Limpieza" },
      { label: "SKU", value: "ELE-003" }
    ],
    tags: ["elementos de limpieza"],
    inStock: true,
  },
  {
    id: "p-033",
    slug: "secador-de-piso-unidad",
    sku: "ELE-004",
    name: "Secador de piso",
    categorySlug: "elementos-de-limpieza",
    price: 350,
    unit: "Unidad",
    minQty: 1,
    images: ["https://picsum.photos/seed/gp-secador-de-piso-unidad/800/800"],
    description: "Secador de piso presentación unidad, de uso profesional para comercios, gastronomía y empresas.",
    specs: [
      { label: "Presentación", value: "Unidad" },
      { label: "Categoría", value: "Elementos de Limpieza" },
      { label: "SKU", value: "ELE-004" }
    ],
    tags: ["elementos de limpieza"],
    inStock: true,
  },
  {
    id: "p-034",
    slug: "lampazo-unidad",
    sku: "ELE-005",
    name: "Lampazo",
    categorySlug: "elementos-de-limpieza",
    price: 360,
    unit: "Unidad",
    minQty: 1,
    images: ["https://picsum.photos/seed/gp-lampazo-unidad/800/800"],
    description: "Lampazo presentación unidad, de uso profesional para comercios, gastronomía y empresas.",
    specs: [
      { label: "Presentación", value: "Unidad" },
      { label: "Categoría", value: "Elementos de Limpieza" },
      { label: "SKU", value: "ELE-005" }
    ],
    tags: ["elementos de limpieza"],
    inStock: true,
  },
  {
    id: "p-035",
    slug: "mopa-algodon-unidad",
    sku: "ELE-006",
    name: "Mopa algodón",
    categorySlug: "elementos-de-limpieza",
    price: 320,
    unit: "Unidad",
    minQty: 1,
    images: ["https://picsum.photos/seed/gp-mopa-algodon-unidad/800/800"],
    description: "Mopa algodón presentación unidad, de uso profesional para comercios, gastronomía y empresas.",
    specs: [
      { label: "Presentación", value: "Unidad" },
      { label: "Categoría", value: "Elementos de Limpieza" },
      { label: "SKU", value: "ELE-006" }
    ],
    tags: ["elementos de limpieza"],
    inStock: true,
  },
  {
    id: "p-036",
    slug: "mopa-microfibra-unidad",
    sku: "ELE-007",
    name: "Mopa microfibra",
    categorySlug: "elementos-de-limpieza",
    price: 420,
    unit: "Unidad",
    minQty: 1,
    images: ["https://picsum.photos/seed/gp-mopa-microfibra-unidad/800/800"],
    description: "Mopa microfibra presentación unidad, de uso profesional para comercios, gastronomía y empresas.",
    specs: [
      { label: "Presentación", value: "Unidad" },
      { label: "Categoría", value: "Elementos de Limpieza" },
      { label: "SKU", value: "ELE-007" }
    ],
    tags: ["elementos de limpieza"],
    inStock: true,
  },
  {
    id: "p-037",
    slug: "mango-metalico-roscado-unidad",
    sku: "ELE-008",
    name: "Mango metálico roscado",
    categorySlug: "elementos-de-limpieza",
    price: 180,
    unit: "Unidad",
    minQty: 1,
    images: ["https://picsum.photos/seed/gp-mango-metalico-roscado-unidad/800/800"],
    description: "Mango metálico roscado presentación unidad, de uso profesional para comercios, gastronomía y empresas.",
    specs: [
      { label: "Presentación", value: "Unidad" },
      { label: "Categoría", value: "Elementos de Limpieza" },
      { label: "SKU", value: "ELE-008" }
    ],
    tags: ["elementos de limpieza"],
    inStock: true,
  },
  {
    id: "p-038",
    slug: "cepillo-de-mano-unidad",
    sku: "ELE-009",
    name: "Cepillo de mano",
    categorySlug: "elementos-de-limpieza",
    price: 160,
    unit: "Unidad",
    minQty: 1,
    images: ["https://picsum.photos/seed/gp-cepillo-de-mano-unidad/800/800"],
    description: "Cepillo de mano presentación unidad, de uso profesional para comercios, gastronomía y empresas.",
    specs: [
      { label: "Presentación", value: "Unidad" },
      { label: "Categoría", value: "Elementos de Limpieza" },
      { label: "SKU", value: "ELE-009" }
    ],
    tags: ["elementos de limpieza"],
    inStock: false,
  },
  {
    id: "p-039",
    slug: "limpiavidrios-con-goma-unidad",
    sku: "ELE-010",
    name: "Limpiavidrios con goma",
    categorySlug: "elementos-de-limpieza",
    price: 210,
    unit: "Unidad",
    minQty: 1,
    images: ["https://picsum.photos/seed/gp-limpiavidrios-con-goma-unidad/800/800"],
    description: "Limpiavidrios con goma presentación unidad, de uso profesional para comercios, gastronomía y empresas.",
    specs: [
      { label: "Presentación", value: "Unidad" },
      { label: "Categoría", value: "Elementos de Limpieza" },
      { label: "SKU", value: "ELE-010" }
    ],
    tags: ["elementos de limpieza"],
    inStock: true,
  },
  {
    id: "p-040",
    slug: "guantes-nitrilo-azul-sin-polvo-caja-x100-unidades-s-m-l",
    sku: "GUA-001",
    name: "Guantes nitrilo azul (sin polvo)",
    categorySlug: "guantes-y-accesorios",
    price: 325,
    unit: "Caja x100 unidades (S/M/L)",
    minQty: 1,
    images: ["https://picsum.photos/seed/gp-guantes-nitrilo-azul-sin-polvo-caja-x100-unidades-s-m-l/800/800"],
    description: "Guantes nitrilo azul (sin polvo) presentación caja x100 unidades (s/m/l), de uso profesional para comercios, gastronomía y empresas.",
    specs: [
      { label: "Presentación", value: "Caja x100 unidades (S/M/L)" },
      { label: "Categoría", value: "Guantes y Accesorios" },
      { label: "SKU", value: "GUA-001" }
    ],
    tags: ["guantes y accesorios"],
    material: "Nitrilo",
    features: ["Sin polvo"],
    inStock: true,
  },
  {
    id: "p-041",
    slug: "guantes-nitrilo-negro-sin-polvo-caja-x100-unidades-s-m-l",
    sku: "GUA-002",
    name: "Guantes nitrilo negro (sin polvo)",
    categorySlug: "guantes-y-accesorios",
    price: 365,
    unit: "Caja x100 unidades (S/M/L)",
    minQty: 1,
    images: ["https://picsum.photos/seed/gp-guantes-nitrilo-negro-sin-polvo-caja-x100-unidades-s-m-l/800/800"],
    description: "Guantes nitrilo negro (sin polvo) presentación caja x100 unidades (s/m/l), de uso profesional para comercios, gastronomía y empresas.",
    specs: [
      { label: "Presentación", value: "Caja x100 unidades (S/M/L)" },
      { label: "Categoría", value: "Guantes y Accesorios" },
      { label: "SKU", value: "GUA-002" }
    ],
    tags: ["guantes y accesorios"],
    material: "Nitrilo",
    features: ["Sin polvo"],
    featured: true,
    inStock: true,
  },
  {
    id: "p-042",
    slug: "guantes-latex-con-polvo-caja-x100-unidades-s-m-l",
    sku: "GUA-003",
    name: "Guantes látex (con polvo)",
    categorySlug: "guantes-y-accesorios",
    price: 220,
    unit: "Caja x100 unidades (S/M/L)",
    minQty: 1,
    images: ["https://picsum.photos/seed/gp-guantes-latex-con-polvo-caja-x100-unidades-s-m-l/800/800"],
    description: "Guantes látex (con polvo) presentación caja x100 unidades (s/m/l), de uso profesional para comercios, gastronomía y empresas.",
    specs: [
      { label: "Presentación", value: "Caja x100 unidades (S/M/L)" },
      { label: "Categoría", value: "Guantes y Accesorios" },
      { label: "SKU", value: "GUA-003" }
    ],
    tags: ["guantes y accesorios"],
    material: "Látex",
    features: ["Con polvo"],
    inStock: true,
  },
  {
    id: "p-043",
    slug: "guantes-vinilo-sin-polvo-caja-x100-unidades-s-m-l",
    sku: "GUA-004",
    name: "Guantes vinilo (sin polvo)",
    categorySlug: "guantes-y-accesorios",
    price: 210,
    unit: "Caja x100 unidades (S/M/L)",
    minQty: 1,
    images: ["https://picsum.photos/seed/gp-guantes-vinilo-sin-polvo-caja-x100-unidades-s-m-l/800/800"],
    description: "Guantes vinilo (sin polvo) presentación caja x100 unidades (s/m/l), de uso profesional para comercios, gastronomía y empresas.",
    specs: [
      { label: "Presentación", value: "Caja x100 unidades (S/M/L)" },
      { label: "Categoría", value: "Guantes y Accesorios" },
      { label: "SKU", value: "GUA-004" }
    ],
    tags: ["guantes y accesorios"],
    material: "Vinilo",
    features: ["Sin polvo"],
    inStock: true,
  },
  {
    id: "p-044",
    slug: "pano-microfibra-unidad",
    sku: "GUA-005",
    name: "Paño microfibra",
    categorySlug: "guantes-y-accesorios",
    price: 65,
    unit: "Unidad",
    minQty: 1,
    images: ["https://picsum.photos/seed/gp-pano-microfibra-unidad/800/800"],
    description: "Paño microfibra presentación unidad, de uso profesional para comercios, gastronomía y empresas.",
    specs: [
      { label: "Presentación", value: "Unidad" },
      { label: "Categoría", value: "Guantes y Accesorios" },
      { label: "SKU", value: "GUA-005" }
    ],
    tags: ["guantes y accesorios"],
    inStock: true,
  },
  {
    id: "p-045",
    slug: "esponja-multiuso-unidad",
    sku: "GUA-006",
    name: "Esponja multiuso",
    categorySlug: "guantes-y-accesorios",
    price: 45,
    unit: "Unidad",
    minQty: 1,
    images: ["https://picsum.photos/seed/gp-esponja-multiuso-unidad/800/800"],
    description: "Esponja multiuso presentación unidad, de uso profesional para comercios, gastronomía y empresas.",
    specs: [
      { label: "Presentación", value: "Unidad" },
      { label: "Categoría", value: "Guantes y Accesorios" },
      { label: "SKU", value: "GUA-006" }
    ],
    tags: ["guantes y accesorios"],
    inStock: true,
  },
  {
    id: "p-046",
    slug: "esponja-industrial-unidad",
    sku: "GUA-007",
    name: "Esponja industrial",
    categorySlug: "guantes-y-accesorios",
    price: 55,
    unit: "Unidad",
    minQty: 1,
    images: ["https://picsum.photos/seed/gp-esponja-industrial-unidad/800/800"],
    description: "Esponja industrial presentación unidad, de uso profesional para comercios, gastronomía y empresas.",
    specs: [
      { label: "Presentación", value: "Unidad" },
      { label: "Categoría", value: "Guantes y Accesorios" },
      { label: "SKU", value: "GUA-007" }
    ],
    tags: ["guantes y accesorios"],
    inStock: true,
  },
  {
    id: "p-047",
    slug: "esponja-de-acero-unidad",
    sku: "GUA-008",
    name: "Esponja de acero",
    categorySlug: "guantes-y-accesorios",
    price: 30,
    unit: "Unidad",
    minQty: 1,
    images: ["https://picsum.photos/seed/gp-esponja-de-acero-unidad/800/800"],
    description: "Esponja de acero presentación unidad, de uso profesional para comercios, gastronomía y empresas.",
    specs: [
      { label: "Presentación", value: "Unidad" },
      { label: "Categoría", value: "Guantes y Accesorios" },
      { label: "SKU", value: "GUA-008" }
    ],
    tags: ["guantes y accesorios"],
    inStock: true,
  },
  {
    id: "p-048",
    slug: "cepillo-de-mano-unidad-guantes-y-accesorios",
    sku: "GUA-009",
    name: "Cepillo de mano",
    categorySlug: "guantes-y-accesorios",
    price: 70,
    unit: "Unidad",
    minQty: 1,
    images: ["https://picsum.photos/seed/gp-cepillo-de-mano-unidad-guantes-y-accesorios/800/800"],
    description: "Cepillo de mano presentación unidad, de uso profesional para comercios, gastronomía y empresas.",
    specs: [
      { label: "Presentación", value: "Unidad" },
      { label: "Categoría", value: "Guantes y Accesorios" },
      { label: "SKU", value: "GUA-009" }
    ],
    tags: ["guantes y accesorios"],
    inStock: true,
  },
  {
    id: "p-049",
    slug: "tapabocas-descartable-caja-x50-unidades",
    sku: "GUA-010",
    name: "Tapabocas descartable",
    categorySlug: "guantes-y-accesorios",
    price: 85,
    unit: "Caja x50 unidades",
    minQty: 1,
    images: ["https://picsum.photos/seed/gp-tapabocas-descartable-caja-x50-unidades/800/800"],
    description: "Tapabocas descartable presentación caja x50 unidades, de uso profesional para comercios, gastronomía y empresas.",
    specs: [
      { label: "Presentación", value: "Caja x50 unidades" },
      { label: "Categoría", value: "Guantes y Accesorios" },
      { label: "SKU", value: "GUA-010" }
    ],
    tags: ["guantes y accesorios"],
    inStock: true,
  },
  {
    id: "p-050",
    slug: "papel-higienico-industrial-pack-x-12-rollos",
    sku: "PAP-001",
    name: "Papel higiénico industrial",
    categorySlug: "papel-e-higiene",
    price: 540,
    unit: "Pack x 12 rollos",
    minQty: 1,
    images: ["https://picsum.photos/seed/gp-papel-higienico-industrial-pack-x-12-rollos/800/800"],
    description: "Papel higiénico industrial presentación pack x 12 rollos, de uso profesional para comercios, gastronomía y empresas.",
    specs: [
      { label: "Presentación", value: "Pack x 12 rollos" },
      { label: "Categoría", value: "Papel e Higiene" },
      { label: "SKU", value: "PAP-001" }
    ],
    tags: ["papel e higiene"],
    featured: true,
    inStock: true,
  },
  {
    id: "p-051",
    slug: "papel-higienico-hogar-pack-x-48-rollos",
    sku: "PAP-002",
    name: "Papel higiénico hogar",
    categorySlug: "papel-e-higiene",
    price: 480,
    unit: "Pack x 48 rollos",
    minQty: 1,
    images: ["https://picsum.photos/seed/gp-papel-higienico-hogar-pack-x-48-rollos/800/800"],
    description: "Papel higiénico hogar presentación pack x 48 rollos, de uso profesional para comercios, gastronomía y empresas.",
    specs: [
      { label: "Presentación", value: "Pack x 48 rollos" },
      { label: "Categoría", value: "Papel e Higiene" },
      { label: "SKU", value: "PAP-002" }
    ],
    tags: ["papel e higiene"],
    inStock: true,
  },
  {
    id: "p-052",
    slug: "toalla-cocina-pack-x-3-rollos",
    sku: "PAP-003",
    name: "Toalla cocina",
    categorySlug: "papel-e-higiene",
    price: 210,
    unit: "Pack x 3 rollos",
    minQty: 1,
    images: ["https://picsum.photos/seed/gp-toalla-cocina-pack-x-3-rollos/800/800"],
    description: "Toalla cocina presentación pack x 3 rollos, de uso profesional para comercios, gastronomía y empresas.",
    specs: [
      { label: "Presentación", value: "Pack x 3 rollos" },
      { label: "Categoría", value: "Papel e Higiene" },
      { label: "SKU", value: "PAP-003" }
    ],
    tags: ["papel e higiene"],
    inStock: true,
  },
  {
    id: "p-053",
    slug: "toalla-interfoliada-pack-x-20-atados",
    sku: "PAP-004",
    name: "Toalla interfoliada",
    categorySlug: "papel-e-higiene",
    price: 590,
    unit: "Pack x 20 atados",
    minQty: 1,
    images: ["https://picsum.photos/seed/gp-toalla-interfoliada-pack-x-20-atados/800/800"],
    description: "Toalla interfoliada presentación pack x 20 atados, de uso profesional para comercios, gastronomía y empresas.",
    specs: [
      { label: "Presentación", value: "Pack x 20 atados" },
      { label: "Categoría", value: "Papel e Higiene" },
      { label: "SKU", value: "PAP-004" }
    ],
    tags: ["papel e higiene"],
    inStock: true,
  },
  {
    id: "p-054",
    slug: "servilletas-pack-x-1000-unidades",
    sku: "PAP-005",
    name: "Servilletas",
    categorySlug: "papel-e-higiene",
    price: 180,
    unit: "Pack x 1000 unidades",
    minQty: 1,
    images: ["https://picsum.photos/seed/gp-servilletas-pack-x-1000-unidades/800/800"],
    description: "Servilletas presentación pack x 1000 unidades, de uso profesional para comercios, gastronomía y empresas.",
    specs: [
      { label: "Presentación", value: "Pack x 1000 unidades" },
      { label: "Categoría", value: "Papel e Higiene" },
      { label: "SKU", value: "PAP-005" }
    ],
    tags: ["papel e higiene"],
    inStock: true,
  },
  {
    id: "p-055",
    slug: "bobinas-industriales-unidad",
    sku: "PAP-006",
    name: "Bobinas industriales",
    categorySlug: "papel-e-higiene",
    price: 950,
    unit: "Unidad",
    minQty: 1,
    images: ["https://picsum.photos/seed/gp-bobinas-industriales-unidad/800/800"],
    description: "Bobinas industriales presentación unidad, de uso profesional para comercios, gastronomía y empresas.",
    specs: [
      { label: "Presentación", value: "Unidad" },
      { label: "Categoría", value: "Papel e Higiene" },
      { label: "SKU", value: "PAP-006" }
    ],
    tags: ["papel e higiene"],
    inStock: true,
  },
  {
    id: "p-056",
    slug: "papel-secamanos-pack-x-6-rollos",
    sku: "PAP-007",
    name: "Papel secamanos",
    categorySlug: "papel-e-higiene",
    price: 420,
    unit: "Pack x 6 rollos",
    minQty: 1,
    images: ["https://picsum.photos/seed/gp-papel-secamanos-pack-x-6-rollos/800/800"],
    description: "Papel secamanos presentación pack x 6 rollos, de uso profesional para comercios, gastronomía y empresas.",
    specs: [
      { label: "Presentación", value: "Pack x 6 rollos" },
      { label: "Categoría", value: "Papel e Higiene" },
      { label: "SKU", value: "PAP-007" }
    ],
    tags: ["papel e higiene"],
    inStock: true,
  },
  {
    id: "p-057",
    slug: "dispensadores-unidad",
    sku: "PAP-008",
    name: "Dispensadores",
    categorySlug: "papel-e-higiene",
    price: 650,
    unit: "Unidad",
    minQty: 1,
    images: ["https://picsum.photos/seed/gp-dispensadores-unidad/800/800"],
    description: "Dispensadores presentación unidad, de uso profesional para comercios, gastronomía y empresas.",
    specs: [
      { label: "Presentación", value: "Unidad" },
      { label: "Categoría", value: "Papel e Higiene" },
      { label: "SKU", value: "PAP-008" }
    ],
    tags: ["papel e higiene"],
    inStock: false,
  },
  {
    id: "p-058",
    slug: "bolsa-camiseta-blanca-10-kg-paq-x1-000",
    sku: "BOL-001",
    name: "Bolsa camiseta blanca",
    categorySlug: "bolsas",
    price: 385,
    unit: "10 kg (paq. x1.000)",
    minQty: 1,
    images: ["https://picsum.photos/seed/gp-bolsa-camiseta-blanca-10-kg-paq-x1-000/800/800"],
    description: "Bolsa camiseta blanca presentación 10 kg (paq. x1.000), de uso profesional para comercios, gastronomía y empresas.",
    specs: [
      { label: "Presentación", value: "10 kg (paq. x1.000)" },
      { label: "Categoría", value: "Bolsas" },
      { label: "SKU", value: "BOL-001" }
    ],
    tags: ["bolsas"],
    inStock: true,
  },
  {
    id: "p-059",
    slug: "bolsa-camiseta-negra-10-kg-paq-x1-000",
    sku: "BOL-002",
    name: "Bolsa camiseta negra",
    categorySlug: "bolsas",
    price: 420,
    unit: "10 kg (paq. x1.000)",
    minQty: 1,
    images: ["https://picsum.photos/seed/gp-bolsa-camiseta-negra-10-kg-paq-x1-000/800/800"],
    description: "Bolsa camiseta negra presentación 10 kg (paq. x1.000), de uso profesional para comercios, gastronomía y empresas.",
    specs: [
      { label: "Presentación", value: "10 kg (paq. x1.000)" },
      { label: "Categoría", value: "Bolsas" },
      { label: "SKU", value: "BOL-002" }
    ],
    tags: ["bolsas"],
    featured: true,
    inStock: true,
  },
  {
    id: "p-060",
    slug: "bolsa-camiseta-transparente-10-kg-paq-x1-000",
    sku: "BOL-003",
    name: "Bolsa camiseta transparente",
    categorySlug: "bolsas",
    price: 360,
    unit: "10 kg (paq. x1.000)",
    minQty: 1,
    images: ["https://picsum.photos/seed/gp-bolsa-camiseta-transparente-10-kg-paq-x1-000/800/800"],
    description: "Bolsa camiseta transparente presentación 10 kg (paq. x1.000), de uso profesional para comercios, gastronomía y empresas.",
    specs: [
      { label: "Presentación", value: "10 kg (paq. x1.000)" },
      { label: "Categoría", value: "Bolsas" },
      { label: "SKU", value: "BOL-003" }
    ],
    tags: ["bolsas"],
    inStock: true,
  },
  {
    id: "p-061",
    slug: "bolsa-consorcio-negra-55x70-cm-paq-x100",
    sku: "BOL-004",
    name: "Bolsa consorcio negra",
    categorySlug: "bolsas",
    price: 140,
    unit: "55x70 cm (paq. x100)",
    minQty: 1,
    images: ["https://picsum.photos/seed/gp-bolsa-consorcio-negra-55x70-cm-paq-x100/800/800"],
    description: "Bolsa consorcio negra presentación 55x70 cm (paq. x100), de uso profesional para comercios, gastronomía y empresas.",
    specs: [
      { label: "Presentación", value: "55x70 cm (paq. x100)" },
      { label: "Categoría", value: "Bolsas" },
      { label: "SKU", value: "BOL-004" }
    ],
    tags: ["bolsas"],
    inStock: true,
  },
  {
    id: "p-062",
    slug: "bolsa-consorcio-negra-70x90-cm-paq-x100",
    sku: "BOL-005",
    name: "Bolsa consorcio negra",
    categorySlug: "bolsas",
    price: 210,
    unit: "70x90 cm (paq. x100)",
    minQty: 1,
    images: ["https://picsum.photos/seed/gp-bolsa-consorcio-negra-70x90-cm-paq-x100/800/800"],
    description: "Bolsa consorcio negra presentación 70x90 cm (paq. x100), de uso profesional para comercios, gastronomía y empresas.",
    specs: [
      { label: "Presentación", value: "70x90 cm (paq. x100)" },
      { label: "Categoría", value: "Bolsas" },
      { label: "SKU", value: "BOL-005" }
    ],
    tags: ["bolsas"],
    inStock: true,
  },
  {
    id: "p-063",
    slug: "bolsa-consorcio-negra-90x110-cm-paq-x100",
    sku: "BOL-006",
    name: "Bolsa consorcio negra",
    categorySlug: "bolsas",
    price: 330,
    unit: "90x110 cm (paq. x100)",
    minQty: 1,
    images: ["https://picsum.photos/seed/gp-bolsa-consorcio-negra-90x110-cm-paq-x100/800/800"],
    description: "Bolsa consorcio negra presentación 90x110 cm (paq. x100), de uso profesional para comercios, gastronomía y empresas.",
    specs: [
      { label: "Presentación", value: "90x110 cm (paq. x100)" },
      { label: "Categoría", value: "Bolsas" },
      { label: "SKU", value: "BOL-006" }
    ],
    tags: ["bolsas"],
    inStock: true,
  },
  {
    id: "p-064",
    slug: "bolsa-para-residuos-blanca-50x60-cm-paq-x100",
    sku: "BOL-007",
    name: "Bolsa para residuos blanca",
    categorySlug: "bolsas",
    price: 120,
    unit: "50x60 cm (paq. x100)",
    minQty: 1,
    images: ["https://picsum.photos/seed/gp-bolsa-para-residuos-blanca-50x60-cm-paq-x100/800/800"],
    description: "Bolsa para residuos blanca presentación 50x60 cm (paq. x100), de uso profesional para comercios, gastronomía y empresas.",
    specs: [
      { label: "Presentación", value: "50x60 cm (paq. x100)" },
      { label: "Categoría", value: "Bolsas" },
      { label: "SKU", value: "BOL-007" }
    ],
    tags: ["bolsas"],
    inStock: true,
  },
  {
    id: "p-065",
    slug: "bolsa-para-residuos-blanca-60x80-cm-paq-x100",
    sku: "BOL-008",
    name: "Bolsa para residuos blanca",
    categorySlug: "bolsas",
    price: 155,
    unit: "60x80 cm (paq. x100)",
    minQty: 1,
    images: ["https://picsum.photos/seed/gp-bolsa-para-residuos-blanca-60x80-cm-paq-x100/800/800"],
    description: "Bolsa para residuos blanca presentación 60x80 cm (paq. x100), de uso profesional para comercios, gastronomía y empresas.",
    specs: [
      { label: "Presentación", value: "60x80 cm (paq. x100)" },
      { label: "Categoría", value: "Bolsas" },
      { label: "SKU", value: "BOL-008" }
    ],
    tags: ["bolsas"],
    inStock: true,
  },
  {
    id: "p-066",
    slug: "bolsa-para-residuos-blanca-70x100-cm-paq-x100",
    sku: "BOL-009",
    name: "Bolsa para residuos blanca",
    categorySlug: "bolsas",
    price: 195,
    unit: "70x100 cm (paq. x100)",
    minQty: 1,
    images: ["https://picsum.photos/seed/gp-bolsa-para-residuos-blanca-70x100-cm-paq-x100/800/800"],
    description: "Bolsa para residuos blanca presentación 70x100 cm (paq. x100), de uso profesional para comercios, gastronomía y empresas.",
    specs: [
      { label: "Presentación", value: "70x100 cm (paq. x100)" },
      { label: "Categoría", value: "Bolsas" },
      { label: "SKU", value: "BOL-009" }
    ],
    tags: ["bolsas"],
    inStock: true,
  },
  {
    id: "p-067",
    slug: "bolsa-en-rollo-alimentos-25x35-cm-rollo-x500",
    sku: "BOL-010",
    name: "Bolsa en rollo (alimentos)",
    categorySlug: "bolsas",
    price: 95,
    unit: "25x35 cm (rollo x500)",
    minQty: 1,
    images: ["https://picsum.photos/seed/gp-bolsa-en-rollo-alimentos-25x35-cm-rollo-x500/800/800"],
    description: "Bolsa en rollo (alimentos) presentación 25x35 cm (rollo x500), de uso profesional para comercios, gastronomía y empresas.",
    specs: [
      { label: "Presentación", value: "25x35 cm (rollo x500)" },
      { label: "Categoría", value: "Bolsas" },
      { label: "SKU", value: "BOL-010" }
    ],
    tags: ["bolsas"],
    inStock: true,
  },
  {
    id: "p-068",
    slug: "bolsa-en-rollo-alimentos-30x40-cm-rollo-x500",
    sku: "BOL-011",
    name: "Bolsa en rollo (alimentos)",
    categorySlug: "bolsas",
    price: 120,
    unit: "30x40 cm (rollo x500)",
    minQty: 1,
    images: ["https://picsum.photos/seed/gp-bolsa-en-rollo-alimentos-30x40-cm-rollo-x500/800/800"],
    description: "Bolsa en rollo (alimentos) presentación 30x40 cm (rollo x500), de uso profesional para comercios, gastronomía y empresas.",
    specs: [
      { label: "Presentación", value: "30x40 cm (rollo x500)" },
      { label: "Categoría", value: "Bolsas" },
      { label: "SKU", value: "BOL-011" }
    ],
    tags: ["bolsas"],
    inStock: true,
  },
  {
    id: "p-069",
    slug: "bolsa-compostable-50x60-cm-paq-x100",
    sku: "BOL-012",
    name: "Bolsa compostable",
    categorySlug: "bolsas",
    price: 195,
    unit: "50x60 cm (paq. x100)",
    minQty: 1,
    images: ["https://picsum.photos/seed/gp-bolsa-compostable-50x60-cm-paq-x100/800/800"],
    description: "Bolsa compostable presentación 50x60 cm (paq. x100), de uso profesional para comercios, gastronomía y empresas.",
    specs: [
      { label: "Presentación", value: "50x60 cm (paq. x100)" },
      { label: "Categoría", value: "Bolsas" },
      { label: "SKU", value: "BOL-012" }
    ],
    tags: ["bolsas"],
    material: "Compostable",
    features: ["Ecológico"],
    inStock: true,
  },
  {
    id: "p-070",
    slug: "bolsa-compostable-60x80-cm-paq-x100",
    sku: "BOL-013",
    name: "Bolsa compostable",
    categorySlug: "bolsas",
    price: 250,
    unit: "60x80 cm (paq. x100)",
    minQty: 1,
    images: ["https://picsum.photos/seed/gp-bolsa-compostable-60x80-cm-paq-x100/800/800"],
    description: "Bolsa compostable presentación 60x80 cm (paq. x100), de uso profesional para comercios, gastronomía y empresas.",
    specs: [
      { label: "Presentación", value: "60x80 cm (paq. x100)" },
      { label: "Categoría", value: "Bolsas" },
      { label: "SKU", value: "BOL-013" }
    ],
    tags: ["bolsas"],
    material: "Compostable",
    features: ["Ecológico"],
    inStock: true,
  },
  {
    id: "p-071",
    slug: "bandeja-aluminio-n6-caja-x-100",
    sku: "BAN-001",
    name: "Bandeja aluminio Nº6",
    categorySlug: "bandejas",
    price: 420,
    unit: "Caja x 100",
    minQty: 1,
    images: ["https://picsum.photos/seed/gp-bandeja-aluminio-n6-caja-x-100/800/800"],
    description: "Bandeja aluminio Nº6 presentación caja x 100, de uso profesional para comercios, gastronomía y empresas.",
    specs: [
      { label: "Presentación", value: "Caja x 100" },
      { label: "Categoría", value: "Bandejas" },
      { label: "SKU", value: "BAN-001" }
    ],
    tags: ["bandejas"],
    material: "Aluminio",
    features: ["Apto horno"],
    inStock: true,
  },
  {
    id: "p-072",
    slug: "bandeja-aluminio-n8-caja-x-100",
    sku: "BAN-002",
    name: "Bandeja aluminio Nº8",
    categorySlug: "bandejas",
    price: 520,
    unit: "Caja x 100",
    minQty: 1,
    images: ["https://picsum.photos/seed/gp-bandeja-aluminio-n8-caja-x-100/800/800"],
    description: "Bandeja aluminio Nº8 presentación caja x 100, de uso profesional para comercios, gastronomía y empresas.",
    specs: [
      { label: "Presentación", value: "Caja x 100" },
      { label: "Categoría", value: "Bandejas" },
      { label: "SKU", value: "BAN-002" }
    ],
    tags: ["bandejas"],
    material: "Aluminio",
    features: ["Apto horno"],
    featured: true,
    inStock: true,
  },
  {
    id: "p-073",
    slug: "bandeja-aluminio-n10-caja-x-100",
    sku: "BAN-003",
    name: "Bandeja aluminio Nº10",
    categorySlug: "bandejas",
    price: 650,
    unit: "Caja x 100",
    minQty: 1,
    images: ["https://picsum.photos/seed/gp-bandeja-aluminio-n10-caja-x-100/800/800"],
    description: "Bandeja aluminio Nº10 presentación caja x 100, de uso profesional para comercios, gastronomía y empresas.",
    specs: [
      { label: "Presentación", value: "Caja x 100" },
      { label: "Categoría", value: "Bandejas" },
      { label: "SKU", value: "BAN-003" }
    ],
    tags: ["bandejas"],
    material: "Aluminio",
    features: ["Apto horno"],
    inStock: true,
  },
  {
    id: "p-074",
    slug: "bandeja-kraft-rectangular-unidad",
    sku: "BAN-004",
    name: "Bandeja kraft rectangular",
    categorySlug: "bandejas",
    price: 110,
    unit: "Unidad",
    minQty: 1,
    images: ["https://picsum.photos/seed/gp-bandeja-kraft-rectangular-unidad/800/800"],
    description: "Bandeja kraft rectangular presentación unidad, de uso profesional para comercios, gastronomía y empresas.",
    specs: [
      { label: "Presentación", value: "Unidad" },
      { label: "Categoría", value: "Bandejas" },
      { label: "SKU", value: "BAN-004" }
    ],
    tags: ["bandejas"],
    material: "Kraft",
    features: ["Apto microondas", "Ecológico"],
    inStock: true,
  },
  {
    id: "p-075",
    slug: "bandeja-kraft-hamburguesa-unidad",
    sku: "BAN-005",
    name: "Bandeja kraft hamburguesa",
    categorySlug: "bandejas",
    price: 85,
    unit: "Unidad",
    minQty: 1,
    images: ["https://picsum.photos/seed/gp-bandeja-kraft-hamburguesa-unidad/800/800"],
    description: "Bandeja kraft hamburguesa presentación unidad, de uso profesional para comercios, gastronomía y empresas.",
    specs: [
      { label: "Presentación", value: "Unidad" },
      { label: "Categoría", value: "Bandejas" },
      { label: "SKU", value: "BAN-005" }
    ],
    tags: ["bandejas"],
    material: "Kraft",
    features: ["Apto microondas", "Ecológico"],
    inStock: true,
  },
  {
    id: "p-076",
    slug: "bandeja-pet-transparente-pack-x-50",
    sku: "BAN-006",
    name: "Bandeja PET transparente",
    categorySlug: "bandejas",
    price: 390,
    unit: "Pack x 50",
    minQty: 1,
    images: ["https://picsum.photos/seed/gp-bandeja-pet-transparente-pack-x-50/800/800"],
    description: "Bandeja PET transparente presentación pack x 50, de uso profesional para comercios, gastronomía y empresas.",
    specs: [
      { label: "Presentación", value: "Pack x 50" },
      { label: "Categoría", value: "Bandejas" },
      { label: "SKU", value: "BAN-006" }
    ],
    tags: ["bandejas"],
    material: "PET",
    features: ["Apto microondas"],
    inStock: true,
  },
  {
    id: "p-077",
    slug: "bandeja-sushi-pack-x-50",
    sku: "BAN-007",
    name: "Bandeja sushi",
    categorySlug: "bandejas",
    price: 430,
    unit: "Pack x 50",
    minQty: 1,
    images: ["https://picsum.photos/seed/gp-bandeja-sushi-pack-x-50/800/800"],
    description: "Bandeja sushi presentación pack x 50, de uso profesional para comercios, gastronomía y empresas.",
    specs: [
      { label: "Presentación", value: "Pack x 50" },
      { label: "Categoría", value: "Bandejas" },
      { label: "SKU", value: "BAN-007" }
    ],
    tags: ["bandejas"],
    inStock: true,
  },
  {
    id: "p-078",
    slug: "bandeja-catering-premium-unidad",
    sku: "BAN-008",
    name: "Bandeja catering premium",
    categorySlug: "bandejas",
    price: 210,
    unit: "Unidad",
    minQty: 1,
    images: ["https://picsum.photos/seed/gp-bandeja-catering-premium-unidad/800/800"],
    description: "Bandeja catering premium presentación unidad, de uso profesional para comercios, gastronomía y empresas.",
    specs: [
      { label: "Presentación", value: "Unidad" },
      { label: "Categoría", value: "Bandejas" },
      { label: "SKU", value: "BAN-008" }
    ],
    tags: ["bandejas"],
    inStock: true,
  },
  {
    id: "p-079",
    slug: "bandeja-descartable-multiuso-pack-x-100",
    sku: "BAN-009",
    name: "Bandeja descartable multiuso",
    categorySlug: "bandejas",
    price: 280,
    unit: "Pack x 100",
    minQty: 1,
    images: ["https://picsum.photos/seed/gp-bandeja-descartable-multiuso-pack-x-100/800/800"],
    description: "Bandeja descartable multiuso presentación pack x 100, de uso profesional para comercios, gastronomía y empresas.",
    specs: [
      { label: "Presentación", value: "Pack x 100" },
      { label: "Categoría", value: "Bandejas" },
      { label: "SKU", value: "BAN-009" }
    ],
    tags: ["bandejas"],
    inStock: true,
  },
  {
    id: "p-080",
    slug: "tapa-para-bandeja-pack-x-100",
    sku: "BAN-010",
    name: "Tapa para bandeja",
    categorySlug: "bandejas",
    price: 230,
    unit: "Pack x 100",
    minQty: 1,
    images: ["https://picsum.photos/seed/gp-tapa-para-bandeja-pack-x-100/800/800"],
    description: "Tapa para bandeja presentación pack x 100, de uso profesional para comercios, gastronomía y empresas.",
    specs: [
      { label: "Presentación", value: "Pack x 100" },
      { label: "Categoría", value: "Bandejas" },
      { label: "SKU", value: "BAN-010" }
    ],
    tags: ["bandejas"],
    inStock: true,
  },
  {
    id: "p-081",
    slug: "caja-pizza-30x30-unidad",
    sku: "CAJ-001",
    name: "Caja pizza 30x30",
    categorySlug: "cajas",
    price: 320,
    unit: "Unidad",
    minQty: 1,
    images: ["https://picsum.photos/seed/gp-caja-pizza-30x30-unidad/800/800"],
    description: "Caja pizza 30x30 presentación unidad, de uso profesional para comercios, gastronomía y empresas.",
    specs: [
      { label: "Presentación", value: "Unidad" },
      { label: "Categoría", value: "Cajas" },
      { label: "SKU", value: "CAJ-001" }
    ],
    tags: ["cajas"],
    inStock: true,
  },
  {
    id: "p-082",
    slug: "caja-pizza-35x35-unidad",
    sku: "CAJ-002",
    name: "Caja pizza 35x35",
    categorySlug: "cajas",
    price: 360,
    unit: "Unidad",
    minQty: 1,
    images: ["https://picsum.photos/seed/gp-caja-pizza-35x35-unidad/800/800"],
    description: "Caja pizza 35x35 presentación unidad, de uso profesional para comercios, gastronomía y empresas.",
    specs: [
      { label: "Presentación", value: "Unidad" },
      { label: "Categoría", value: "Cajas" },
      { label: "SKU", value: "CAJ-002" }
    ],
    tags: ["cajas"],
    featured: true,
    inStock: true,
  },
  {
    id: "p-083",
    slug: "caja-pizza-40x40-unidad",
    sku: "CAJ-003",
    name: "Caja pizza 40x40",
    categorySlug: "cajas",
    price: 420,
    unit: "Unidad",
    minQty: 1,
    images: ["https://picsum.photos/seed/gp-caja-pizza-40x40-unidad/800/800"],
    description: "Caja pizza 40x40 presentación unidad, de uso profesional para comercios, gastronomía y empresas.",
    specs: [
      { label: "Presentación", value: "Unidad" },
      { label: "Categoría", value: "Cajas" },
      { label: "SKU", value: "CAJ-003" }
    ],
    tags: ["cajas"],
    inStock: false,
  },
  {
    id: "p-084",
    slug: "caja-hamburguesa-kraft-unidad",
    sku: "CAJ-004",
    name: "Caja hamburguesa kraft",
    categorySlug: "cajas",
    price: 85,
    unit: "Unidad",
    minQty: 1,
    images: ["https://picsum.photos/seed/gp-caja-hamburguesa-kraft-unidad/800/800"],
    description: "Caja hamburguesa kraft presentación unidad, de uso profesional para comercios, gastronomía y empresas.",
    specs: [
      { label: "Presentación", value: "Unidad" },
      { label: "Categoría", value: "Cajas" },
      { label: "SKU", value: "CAJ-004" }
    ],
    tags: ["cajas"],
    material: "Kraft",
    features: ["Apto microondas", "Ecológico"],
    inStock: true,
  },
  {
    id: "p-085",
    slug: "caja-torta-unidad",
    sku: "CAJ-005",
    name: "Caja torta",
    categorySlug: "cajas",
    price: 140,
    unit: "Unidad",
    minQty: 1,
    images: ["https://picsum.photos/seed/gp-caja-torta-unidad/800/800"],
    description: "Caja torta presentación unidad, de uso profesional para comercios, gastronomía y empresas.",
    specs: [
      { label: "Presentación", value: "Unidad" },
      { label: "Categoría", value: "Cajas" },
      { label: "SKU", value: "CAJ-005" }
    ],
    tags: ["cajas"],
    inStock: true,
  },
  {
    id: "p-086",
    slug: "caja-delivery-mediana-unidad",
    sku: "CAJ-006",
    name: "Caja delivery mediana",
    categorySlug: "cajas",
    price: 180,
    unit: "Unidad",
    minQty: 1,
    images: ["https://picsum.photos/seed/gp-caja-delivery-mediana-unidad/800/800"],
    description: "Caja delivery mediana presentación unidad, de uso profesional para comercios, gastronomía y empresas.",
    specs: [
      { label: "Presentación", value: "Unidad" },
      { label: "Categoría", value: "Cajas" },
      { label: "SKU", value: "CAJ-006" }
    ],
    tags: ["cajas"],
    inStock: true,
  },
  {
    id: "p-087",
    slug: "caja-delivery-grande-unidad",
    sku: "CAJ-007",
    name: "Caja delivery grande",
    categorySlug: "cajas",
    price: 240,
    unit: "Unidad",
    minQty: 1,
    images: ["https://picsum.photos/seed/gp-caja-delivery-grande-unidad/800/800"],
    description: "Caja delivery grande presentación unidad, de uso profesional para comercios, gastronomía y empresas.",
    specs: [
      { label: "Presentación", value: "Unidad" },
      { label: "Categoría", value: "Cajas" },
      { label: "SKU", value: "CAJ-007" }
    ],
    tags: ["cajas"],
    inStock: true,
  },
  {
    id: "p-088",
    slug: "caja-kraft-con-ventana-unidad",
    sku: "CAJ-008",
    name: "Caja kraft con ventana",
    categorySlug: "cajas",
    price: 160,
    unit: "Unidad",
    minQty: 1,
    images: ["https://picsum.photos/seed/gp-caja-kraft-con-ventana-unidad/800/800"],
    description: "Caja kraft con ventana presentación unidad, de uso profesional para comercios, gastronomía y empresas.",
    specs: [
      { label: "Presentación", value: "Unidad" },
      { label: "Categoría", value: "Cajas" },
      { label: "SKU", value: "CAJ-008" }
    ],
    tags: ["cajas"],
    material: "Kraft",
    features: ["Apto microondas", "Ecológico"],
    inStock: true,
  },
  {
    id: "p-089",
    slug: "caja-sandwich-unidad",
    sku: "CAJ-009",
    name: "Caja sandwich",
    categorySlug: "cajas",
    price: 70,
    unit: "Unidad",
    minQty: 1,
    images: ["https://picsum.photos/seed/gp-caja-sandwich-unidad/800/800"],
    description: "Caja sandwich presentación unidad, de uso profesional para comercios, gastronomía y empresas.",
    specs: [
      { label: "Presentación", value: "Unidad" },
      { label: "Categoría", value: "Cajas" },
      { label: "SKU", value: "CAJ-009" }
    ],
    tags: ["cajas"],
    inStock: true,
  },
  {
    id: "p-090",
    slug: "caja-personalizada-unidad",
    sku: "CAJ-010",
    name: "Caja personalizada",
    categorySlug: "cajas",
    price: 250,
    unit: "Unidad",
    minQty: 1,
    images: ["https://picsum.photos/seed/gp-caja-personalizada-unidad/800/800"],
    description: "Caja personalizada presentación unidad, de uso profesional para comercios, gastronomía y empresas.",
    specs: [
      { label: "Presentación", value: "Unidad" },
      { label: "Categoría", value: "Cajas" },
      { label: "SKU", value: "CAJ-010" }
    ],
    tags: ["cajas"],
    inStock: true,
  },
  {
    id: "p-091",
    slug: "vaso-plastico-200-cc-pack-x-100",
    sku: "VAS-001",
    name: "Vaso plástico 200 cc",
    categorySlug: "vasos-y-tapas",
    price: 120,
    unit: "Pack x 100",
    minQty: 1,
    images: ["https://picsum.photos/seed/gp-vaso-plastico-200-cc-pack-x-100/800/800"],
    description: "Vaso plástico 200 cc presentación pack x 100, de uso profesional para comercios, gastronomía y empresas.",
    specs: [
      { label: "Presentación", value: "Pack x 100" },
      { label: "Categoría", value: "Vasos y Tapas" },
      { label: "SKU", value: "VAS-001" }
    ],
    tags: ["vasos y tapas"],
    material: "Plástico",
    inStock: true,
  },
  {
    id: "p-092",
    slug: "vaso-plastico-300-cc-pack-x-100",
    sku: "VAS-002",
    name: "Vaso plástico 300 cc",
    categorySlug: "vasos-y-tapas",
    price: 150,
    unit: "Pack x 100",
    minQty: 1,
    images: ["https://picsum.photos/seed/gp-vaso-plastico-300-cc-pack-x-100/800/800"],
    description: "Vaso plástico 300 cc presentación pack x 100, de uso profesional para comercios, gastronomía y empresas.",
    specs: [
      { label: "Presentación", value: "Pack x 100" },
      { label: "Categoría", value: "Vasos y Tapas" },
      { label: "SKU", value: "VAS-002" }
    ],
    tags: ["vasos y tapas"],
    material: "Plástico",
    inStock: true,
  },
  {
    id: "p-093",
    slug: "vaso-plastico-500-cc-pack-x-100",
    sku: "VAS-003",
    name: "Vaso plástico 500 cc",
    categorySlug: "vasos-y-tapas",
    price: 180,
    unit: "Pack x 100",
    minQty: 1,
    images: ["https://picsum.photos/seed/gp-vaso-plastico-500-cc-pack-x-100/800/800"],
    description: "Vaso plástico 500 cc presentación pack x 100, de uso profesional para comercios, gastronomía y empresas.",
    specs: [
      { label: "Presentación", value: "Pack x 100" },
      { label: "Categoría", value: "Vasos y Tapas" },
      { label: "SKU", value: "VAS-003" }
    ],
    tags: ["vasos y tapas"],
    material: "Plástico",
    featured: true,
    inStock: true,
  },
  {
    id: "p-094",
    slug: "vaso-plastico-700-cc-pack-x-100",
    sku: "VAS-004",
    name: "Vaso plástico 700 cc",
    categorySlug: "vasos-y-tapas",
    price: 220,
    unit: "Pack x 100",
    minQty: 1,
    images: ["https://picsum.photos/seed/gp-vaso-plastico-700-cc-pack-x-100/800/800"],
    description: "Vaso plástico 700 cc presentación pack x 100, de uso profesional para comercios, gastronomía y empresas.",
    specs: [
      { label: "Presentación", value: "Pack x 100" },
      { label: "Categoría", value: "Vasos y Tapas" },
      { label: "SKU", value: "VAS-004" }
    ],
    tags: ["vasos y tapas"],
    material: "Plástico",
    inStock: true,
  },
  {
    id: "p-095",
    slug: "vaso-papel-8-oz-pack-x-50",
    sku: "VAS-005",
    name: "Vaso papel 8 oz",
    categorySlug: "vasos-y-tapas",
    price: 220,
    unit: "Pack x 50",
    minQty: 1,
    images: ["https://picsum.photos/seed/gp-vaso-papel-8-oz-pack-x-50/800/800"],
    description: "Vaso papel 8 oz presentación pack x 50, de uso profesional para comercios, gastronomía y empresas.",
    specs: [
      { label: "Presentación", value: "Pack x 50" },
      { label: "Categoría", value: "Vasos y Tapas" },
      { label: "SKU", value: "VAS-005" }
    ],
    tags: ["vasos y tapas"],
    material: "Papel",
    inStock: true,
  },
  {
    id: "p-096",
    slug: "vaso-papel-12-oz-pack-x-50",
    sku: "VAS-006",
    name: "Vaso papel 12 oz",
    categorySlug: "vasos-y-tapas",
    price: 280,
    unit: "Pack x 50",
    minQty: 1,
    images: ["https://picsum.photos/seed/gp-vaso-papel-12-oz-pack-x-50/800/800"],
    description: "Vaso papel 12 oz presentación pack x 50, de uso profesional para comercios, gastronomía y empresas.",
    specs: [
      { label: "Presentación", value: "Pack x 50" },
      { label: "Categoría", value: "Vasos y Tapas" },
      { label: "SKU", value: "VAS-006" }
    ],
    tags: ["vasos y tapas"],
    material: "Papel",
    inStock: true,
  },
  {
    id: "p-097",
    slug: "tapa-plana-para-vaso-pack-x-100",
    sku: "VAS-007",
    name: "Tapa plana para vaso",
    categorySlug: "vasos-y-tapas",
    price: 120,
    unit: "Pack x 100",
    minQty: 1,
    images: ["https://picsum.photos/seed/gp-tapa-plana-para-vaso-pack-x-100/800/800"],
    description: "Tapa plana para vaso presentación pack x 100, de uso profesional para comercios, gastronomía y empresas.",
    specs: [
      { label: "Presentación", value: "Pack x 100" },
      { label: "Categoría", value: "Vasos y Tapas" },
      { label: "SKU", value: "VAS-007" }
    ],
    tags: ["vasos y tapas"],
    inStock: true,
  },
  {
    id: "p-098",
    slug: "tapa-domo-para-vaso-pack-x-100",
    sku: "VAS-008",
    name: "Tapa domo para vaso",
    categorySlug: "vasos-y-tapas",
    price: 140,
    unit: "Pack x 100",
    minQty: 1,
    images: ["https://picsum.photos/seed/gp-tapa-domo-para-vaso-pack-x-100/800/800"],
    description: "Tapa domo para vaso presentación pack x 100, de uso profesional para comercios, gastronomía y empresas.",
    specs: [
      { label: "Presentación", value: "Pack x 100" },
      { label: "Categoría", value: "Vasos y Tapas" },
      { label: "SKU", value: "VAS-008" }
    ],
    tags: ["vasos y tapas"],
    inStock: true,
  },
  {
    id: "p-099",
    slug: "tapa-con-pico-pack-x-100",
    sku: "VAS-009",
    name: "Tapa con pico",
    categorySlug: "vasos-y-tapas",
    price: 150,
    unit: "Pack x 100",
    minQty: 1,
    images: ["https://picsum.photos/seed/gp-tapa-con-pico-pack-x-100/800/800"],
    description: "Tapa con pico presentación pack x 100, de uso profesional para comercios, gastronomía y empresas.",
    specs: [
      { label: "Presentación", value: "Pack x 100" },
      { label: "Categoría", value: "Vasos y Tapas" },
      { label: "SKU", value: "VAS-009" }
    ],
    tags: ["vasos y tapas"],
    inStock: true,
  },
  {
    id: "p-100",
    slug: "portavaso-termico-pack-x-50",
    sku: "VAS-010",
    name: "Portavaso térmico",
    categorySlug: "vasos-y-tapas",
    price: 200,
    unit: "Pack x 50",
    minQty: 1,
    images: ["https://picsum.photos/seed/gp-portavaso-termico-pack-x-50/800/800"],
    description: "Portavaso térmico presentación pack x 50, de uso profesional para comercios, gastronomía y empresas.",
    specs: [
      { label: "Presentación", value: "Pack x 50" },
      { label: "Categoría", value: "Vasos y Tapas" },
      { label: "SKU", value: "VAS-010" }
    ],
    tags: ["vasos y tapas"],
    features: ["Térmico"],
    inStock: true,
  },
  {
    id: "p-101",
    slug: "bowl-kraft-500-cc-pack-x-50",
    sku: "BOW-001",
    name: "Bowl Kraft 500 cc",
    categorySlug: "bowls-y-contenedores",
    price: 250,
    unit: "Pack x 50",
    minQty: 1,
    images: ["https://picsum.photos/seed/gp-bowl-kraft-500-cc-pack-x-50/800/800"],
    description: "Bowl Kraft 500 cc presentación pack x 50, de uso profesional para comercios, gastronomía y empresas.",
    specs: [
      { label: "Presentación", value: "Pack x 50" },
      { label: "Categoría", value: "Bowls y Contenedores" },
      { label: "SKU", value: "BOW-001" }
    ],
    tags: ["bowls y contenedores"],
    material: "Kraft",
    features: ["Apto microondas", "Ecológico"],
    inStock: true,
  },
  {
    id: "p-102",
    slug: "bowl-kraft-750-cc-pack-x-50",
    sku: "BOW-002",
    name: "Bowl Kraft 750 cc",
    categorySlug: "bowls-y-contenedores",
    price: 295,
    unit: "Pack x 50",
    minQty: 1,
    images: ["https://picsum.photos/seed/gp-bowl-kraft-750-cc-pack-x-50/800/800"],
    description: "Bowl Kraft 750 cc presentación pack x 50, de uso profesional para comercios, gastronomía y empresas.",
    specs: [
      { label: "Presentación", value: "Pack x 50" },
      { label: "Categoría", value: "Bowls y Contenedores" },
      { label: "SKU", value: "BOW-002" }
    ],
    tags: ["bowls y contenedores"],
    material: "Kraft",
    features: ["Apto microondas", "Ecológico"],
    featured: true,
    inStock: true,
  },
  {
    id: "p-103",
    slug: "bowl-kraft-1000-cc-pack-x-50",
    sku: "BOW-003",
    name: "Bowl Kraft 1000 cc",
    categorySlug: "bowls-y-contenedores",
    price: 350,
    unit: "Pack x 50",
    minQty: 1,
    images: ["https://picsum.photos/seed/gp-bowl-kraft-1000-cc-pack-x-50/800/800"],
    description: "Bowl Kraft 1000 cc presentación pack x 50, de uso profesional para comercios, gastronomía y empresas.",
    specs: [
      { label: "Presentación", value: "Pack x 50" },
      { label: "Categoría", value: "Bowls y Contenedores" },
      { label: "SKU", value: "BOW-003" }
    ],
    tags: ["bowls y contenedores"],
    material: "Kraft",
    features: ["Apto microondas", "Ecológico"],
    inStock: true,
  },
  {
    id: "p-104",
    slug: "contenedor-rectangular-chico-pack-x-50",
    sku: "BOW-004",
    name: "Contenedor Rectangular Chico",
    categorySlug: "bowls-y-contenedores",
    price: 290,
    unit: "Pack x 50",
    minQty: 1,
    images: ["https://picsum.photos/seed/gp-contenedor-rectangular-chico-pack-x-50/800/800"],
    description: "Contenedor Rectangular Chico presentación pack x 50, de uso profesional para comercios, gastronomía y empresas.",
    specs: [
      { label: "Presentación", value: "Pack x 50" },
      { label: "Categoría", value: "Bowls y Contenedores" },
      { label: "SKU", value: "BOW-004" }
    ],
    tags: ["bowls y contenedores"],
    inStock: false,
  },
  {
    id: "p-105",
    slug: "contenedor-rectangular-mediano-pack-x-50",
    sku: "BOW-005",
    name: "Contenedor Rectangular Mediano",
    categorySlug: "bowls-y-contenedores",
    price: 340,
    unit: "Pack x 50",
    minQty: 1,
    images: ["https://picsum.photos/seed/gp-contenedor-rectangular-mediano-pack-x-50/800/800"],
    description: "Contenedor Rectangular Mediano presentación pack x 50, de uso profesional para comercios, gastronomía y empresas.",
    specs: [
      { label: "Presentación", value: "Pack x 50" },
      { label: "Categoría", value: "Bowls y Contenedores" },
      { label: "SKU", value: "BOW-005" }
    ],
    tags: ["bowls y contenedores"],
    inStock: true,
  },
  {
    id: "p-106",
    slug: "contenedor-rectangular-grande-pack-x-50",
    sku: "BOW-006",
    name: "Contenedor Rectangular Grande",
    categorySlug: "bowls-y-contenedores",
    price: 410,
    unit: "Pack x 50",
    minQty: 1,
    images: ["https://picsum.photos/seed/gp-contenedor-rectangular-grande-pack-x-50/800/800"],
    description: "Contenedor Rectangular Grande presentación pack x 50, de uso profesional para comercios, gastronomía y empresas.",
    specs: [
      { label: "Presentación", value: "Pack x 50" },
      { label: "Categoría", value: "Bowls y Contenedores" },
      { label: "SKU", value: "BOW-006" }
    ],
    tags: ["bowls y contenedores"],
    inStock: true,
  },
  {
    id: "p-107",
    slug: "pote-salsa-pack-x-100",
    sku: "BOW-007",
    name: "Pote Salsa",
    categorySlug: "bowls-y-contenedores",
    price: 190,
    unit: "Pack x 100",
    minQty: 1,
    images: ["https://picsum.photos/seed/gp-pote-salsa-pack-x-100/800/800"],
    description: "Pote Salsa presentación pack x 100, de uso profesional para comercios, gastronomía y empresas.",
    specs: [
      { label: "Presentación", value: "Pack x 100" },
      { label: "Categoría", value: "Bowls y Contenedores" },
      { label: "SKU", value: "BOW-007" }
    ],
    tags: ["bowls y contenedores"],
    inStock: true,
  },
  {
    id: "p-108",
    slug: "tapa-bowl-kraft-pack-x-50",
    sku: "BOW-008",
    name: "Tapa Bowl Kraft",
    categorySlug: "bowls-y-contenedores",
    price: 160,
    unit: "Pack x 50",
    minQty: 1,
    images: ["https://picsum.photos/seed/gp-tapa-bowl-kraft-pack-x-50/800/800"],
    description: "Tapa Bowl Kraft presentación pack x 50, de uso profesional para comercios, gastronomía y empresas.",
    specs: [
      { label: "Presentación", value: "Pack x 50" },
      { label: "Categoría", value: "Bowls y Contenedores" },
      { label: "SKU", value: "BOW-008" }
    ],
    tags: ["bowls y contenedores"],
    material: "Kraft",
    features: ["Apto microondas", "Ecológico"],
    inStock: true,
  },
  {
    id: "p-109",
    slug: "tapa-pet-transparente-pack-x-50",
    sku: "BOW-009",
    name: "Tapa PET Transparente",
    categorySlug: "bowls-y-contenedores",
    price: 175,
    unit: "Pack x 50",
    minQty: 1,
    images: ["https://picsum.photos/seed/gp-tapa-pet-transparente-pack-x-50/800/800"],
    description: "Tapa PET Transparente presentación pack x 50, de uso profesional para comercios, gastronomía y empresas.",
    specs: [
      { label: "Presentación", value: "Pack x 50" },
      { label: "Categoría", value: "Bowls y Contenedores" },
      { label: "SKU", value: "BOW-009" }
    ],
    tags: ["bowls y contenedores"],
    material: "PET",
    features: ["Apto microondas"],
    inStock: true,
  },
  {
    id: "p-110",
    slug: "contenedor-ecologico-pack-x-50",
    sku: "BOW-010",
    name: "Contenedor Ecológico",
    categorySlug: "bowls-y-contenedores",
    price: 330,
    unit: "Pack x 50",
    minQty: 1,
    images: ["https://picsum.photos/seed/gp-contenedor-ecologico-pack-x-50/800/800"],
    description: "Contenedor Ecológico presentación pack x 50, de uso profesional para comercios, gastronomía y empresas.",
    specs: [
      { label: "Presentación", value: "Pack x 50" },
      { label: "Categoría", value: "Bowls y Contenedores" },
      { label: "SKU", value: "BOW-010" }
    ],
    tags: ["bowls y contenedores"],
    inStock: true,
  },
  {
    id: "p-111",
    slug: "cinta-adhesiva-transparente-unidad",
    sku: "OFI-001",
    name: "Cinta adhesiva transparente",
    categorySlug: "papeleria",
    price: 80,
    unit: "Unidad",
    minQty: 1,
    images: ["https://picsum.photos/seed/gp-cinta-adhesiva-transparente-unidad/800/800"],
    description: "Cinta adhesiva transparente presentación unidad, de uso profesional para comercios, gastronomía y empresas.",
    specs: [
      { label: "Presentación", value: "Unidad" },
      { label: "Categoría", value: "Papelería" },
      { label: "SKU", value: "OFI-001" }
    ],
    tags: ["papelería"],
    inStock: true,
  },
  {
    id: "p-112",
    slug: "cinta-adhesiva-ancha-unidad",
    sku: "OFI-002",
    name: "Cinta adhesiva ancha",
    categorySlug: "papeleria",
    price: 120,
    unit: "Unidad",
    minQty: 1,
    images: ["https://picsum.photos/seed/gp-cinta-adhesiva-ancha-unidad/800/800"],
    description: "Cinta adhesiva ancha presentación unidad, de uso profesional para comercios, gastronomía y empresas.",
    specs: [
      { label: "Presentación", value: "Unidad" },
      { label: "Categoría", value: "Papelería" },
      { label: "SKU", value: "OFI-002" }
    ],
    tags: ["papelería"],
    inStock: true,
  },
  {
    id: "p-113",
    slug: "marcador-permanente-unidad",
    sku: "OFI-003",
    name: "Marcador permanente",
    categorySlug: "papeleria",
    price: 70,
    unit: "Unidad",
    minQty: 1,
    images: ["https://picsum.photos/seed/gp-marcador-permanente-unidad/800/800"],
    description: "Marcador permanente presentación unidad, de uso profesional para comercios, gastronomía y empresas.",
    specs: [
      { label: "Presentación", value: "Unidad" },
      { label: "Categoría", value: "Papelería" },
      { label: "SKU", value: "OFI-003" }
    ],
    tags: ["papelería"],
    inStock: true,
  },
  {
    id: "p-114",
    slug: "resaltador-unidad",
    sku: "OFI-004",
    name: "Resaltador",
    categorySlug: "papeleria",
    price: 45,
    unit: "Unidad",
    minQty: 1,
    images: ["https://picsum.photos/seed/gp-resaltador-unidad/800/800"],
    description: "Resaltador presentación unidad, de uso profesional para comercios, gastronomía y empresas.",
    specs: [
      { label: "Presentación", value: "Unidad" },
      { label: "Categoría", value: "Papelería" },
      { label: "SKU", value: "OFI-004" }
    ],
    tags: ["papelería"],
    inStock: true,
  },
  {
    id: "p-115",
    slug: "hojas-a4-resma",
    sku: "OFI-005",
    name: "Hojas A4",
    categorySlug: "papeleria",
    price: 250,
    unit: "Resma",
    minQty: 1,
    images: ["https://picsum.photos/seed/gp-hojas-a4-resma/800/800"],
    description: "Hojas A4 presentación resma, de uso profesional para comercios, gastronomía y empresas.",
    specs: [
      { label: "Presentación", value: "Resma" },
      { label: "Categoría", value: "Papelería" },
      { label: "SKU", value: "OFI-005" }
    ],
    tags: ["papelería"],
    inStock: true,
  },
  {
    id: "p-116",
    slug: "etiquetas-adhesivas-pack",
    sku: "OFI-006",
    name: "Etiquetas adhesivas",
    categorySlug: "papeleria",
    price: 130,
    unit: "Pack",
    minQty: 1,
    images: ["https://picsum.photos/seed/gp-etiquetas-adhesivas-pack/800/800"],
    description: "Etiquetas adhesivas presentación pack, de uso profesional para comercios, gastronomía y empresas.",
    specs: [
      { label: "Presentación", value: "Pack" },
      { label: "Categoría", value: "Papelería" },
      { label: "SKU", value: "OFI-006" }
    ],
    tags: ["papelería"],
    inStock: true,
  },
  {
    id: "p-117",
    slug: "engrampadora-unidad",
    sku: "OFI-007",
    name: "Engrampadora",
    categorySlug: "papeleria",
    price: 180,
    unit: "Unidad",
    minQty: 1,
    images: ["https://picsum.photos/seed/gp-engrampadora-unidad/800/800"],
    description: "Engrampadora presentación unidad, de uso profesional para comercios, gastronomía y empresas.",
    specs: [
      { label: "Presentación", value: "Unidad" },
      { label: "Categoría", value: "Papelería" },
      { label: "SKU", value: "OFI-007" }
    ],
    tags: ["papelería"],
    inStock: true,
  },
  {
    id: "p-118",
    slug: "grapas-caja",
    sku: "OFI-008",
    name: "Grapas",
    categorySlug: "papeleria",
    price: 60,
    unit: "Caja",
    minQty: 1,
    images: ["https://picsum.photos/seed/gp-grapas-caja/800/800"],
    description: "Grapas presentación caja, de uso profesional para comercios, gastronomía y empresas.",
    specs: [
      { label: "Presentación", value: "Caja" },
      { label: "Categoría", value: "Papelería" },
      { label: "SKU", value: "OFI-008" }
    ],
    tags: ["papelería"],
    inStock: true,
  },
  {
    id: "p-119",
    slug: "rollo-pos-unidad",
    sku: "OFI-009",
    name: "Rollo POS",
    categorySlug: "papeleria",
    price: 35,
    unit: "Unidad",
    minQty: 1,
    images: ["https://picsum.photos/seed/gp-rollo-pos-unidad/800/800"],
    description: "Rollo POS presentación unidad, de uso profesional para comercios, gastronomía y empresas.",
    specs: [
      { label: "Presentación", value: "Unidad" },
      { label: "Categoría", value: "Papelería" },
      { label: "SKU", value: "OFI-009" }
    ],
    tags: ["papelería"],
    inStock: true,
  },
  {
    id: "p-120",
    slug: "corrector-unidad",
    sku: "OFI-010",
    name: "Corrector",
    categorySlug: "papeleria",
    price: 70,
    unit: "Unidad",
    minQty: 1,
    images: ["https://picsum.photos/seed/gp-corrector-unidad/800/800"],
    description: "Corrector presentación unidad, de uso profesional para comercios, gastronomía y empresas.",
    specs: [
      { label: "Presentación", value: "Unidad" },
      { label: "Categoría", value: "Papelería" },
      { label: "SKU", value: "OFI-010" }
    ],
    tags: ["papelería"],
    inStock: true,
  }
];

export function getCategoryBySlug(slug: string) {
  return categories.find((c) => c.slug === slug);
}

export function getProductBySlug(slug: string) {
  return products.find((p) => p.slug === slug);
}

export function getProductsByCategory(slug: string) {
  return products.filter((p) => p.categorySlug === slug);
}

export function getRelatedProducts(product: Product, limit = 4) {
  return products
    .filter((p) => p.categorySlug === product.categorySlug && p.id !== product.id)
    .slice(0, limit);
}

export function getFeaturedProducts() {
  return products.filter((p) => p.featured);
}
