import {
  Droplet,
  Droplets,
  Brush,
  Hand,
  HandMetal,
  Layers,
  StickyNote,
  ShoppingBag,
  Square,
  Box,
  PackageOpen,
  CupSoda,
  Circle,
  Soup,
  PenTool,
  SprayCan,
  Trash2,
  Paperclip,
  Palette,
  Package,
  Sparkles,
  Waves,
  type LucideIcon,
} from "lucide-react";

// Keyword → icon, most specific first. Matched against the lowercased product name.
const KEYWORD_ICONS: [string, LucideIcon][] = [
  ["alcohol en gel", Droplets],
  ["alcohol", Droplet],
  ["amonio", SprayCan],
  ["cera", Sparkles],
  ["desengrasante", SprayCan],
  ["detergente", Droplets],
  ["hipoclorito", Droplets],
  ["lavandina", Droplets],
  ["lavavajillas", Droplets],
  ["limpia horno", SprayCan],
  ["limpia vidrio", SprayCan],
  ["limpiador", SprayCan],
  ["saca sarro", SprayCan],
  ["aromatizante", Waves],
  ["desinfectante", SprayCan],
  ["jabón", Droplet],
  ["suavizante", Waves],
  ["balde", Trash2],
  ["basurero", Trash2],
  ["escoba", Brush],
  ["pala de mano", Brush],
  ["secador de piso", Brush],
  ["lampazo", Brush],
  ["mopa", Brush],
  ["mango metálico", Brush],
  ["cepillo", Brush],
  ["limpiavidrios", SprayCan],
  ["guante", Hand],
  ["paño", Square],
  ["esponja", Square],
  ["tapabocas", HandMetal],
  ["papel higiénico", Layers],
  ["toalla", Layers],
  ["servilleta", StickyNote],
  ["bobina", Layers],
  ["papel secamanos", Layers],
  ["dispensador", PackageOpen],
  ["bolsa", ShoppingBag],
  ["bandeja", Square],
  ["tapa para bandeja", Circle],
  ["caja", Box],
  ["vaso", CupSoda],
  ["tapa", Circle],
  ["portavaso", CupSoda],
  ["bowl", Soup],
  ["contenedor", Soup],
  ["pote", Soup],
  ["cinta adhesiva", Paperclip],
  ["marcador", PenTool],
  ["resaltador", PenTool],
  ["hojas a4", StickyNote],
  ["etiquetas", StickyNote],
  ["engrampadora", Paperclip],
  ["grapas", Paperclip],
  ["rollo pos", Layers],
  ["corrector", PenTool],
];

const CATEGORY_ICONS: Record<string, LucideIcon> = {
  "limpieza": SprayCan,
  "higiene-personal-y-lavado": Droplet,
  "baldes-y-residuos": Trash2,
  "elementos-de-limpieza": Brush,
  "guantes-y-accesorios": Hand,
  "papel-e-higiene": Layers,
  "bolsas": ShoppingBag,
  "bandejas": Square,
  "cajas": Box,
  "vasos-y-tapas": CupSoda,
  "bowls-y-contenedores": Soup,
  "papeleria": PenTool,
  "packaging-personalizado": Palette,
};

const CATEGORY_TINTS: Record<string, string> = {
  "limpieza": "bg-sky-50 text-sky-700",
  "higiene-personal-y-lavado": "bg-violet-50 text-violet-700",
  "baldes-y-residuos": "bg-slate-100 text-slate-700",
  "elementos-de-limpieza": "bg-emerald-50 text-emerald-700",
  "guantes-y-accesorios": "bg-amber-50 text-amber-700",
  "papel-e-higiene": "bg-cyan-50 text-cyan-700",
  "bolsas": "bg-lime-50 text-lime-700",
  "bandejas": "bg-orange-50 text-orange-700",
  "cajas": "bg-yellow-50 text-yellow-800",
  "vasos-y-tapas": "bg-rose-50 text-rose-700",
  "bowls-y-contenedores": "bg-teal-50 text-teal-700",
  "papeleria": "bg-indigo-50 text-indigo-700",
  "packaging-personalizado": "bg-fuchsia-50 text-fuchsia-700",
};

export function getProductIcon(name: string, categorySlug: string): LucideIcon {
  const n = name.toLowerCase();
  for (const [keyword, Icon] of KEYWORD_ICONS) {
    if (n.includes(keyword)) return Icon;
  }
  return CATEGORY_ICONS[categorySlug] ?? Package;
}

export function getCategoryTint(categorySlug: string): string {
  return CATEGORY_TINTS[categorySlug] ?? "bg-paper text-ink-soft";
}
